# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go get github.com/markbates/pkger/cmd/pkger
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
    -s -w -X github.com/marema31/kin/cmd.version={{.Version}} -X github.com/marema31/kin/cmd.commit={{.ShortCommit}} -X github.com/marema31/kin/cmd.date={{.Date}}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: marema31
    name: kin
brews:
  - github:
      owner: marema31
      name: homebrew-marema31
    description: "Automatic home page of self hosted dockerized web application"
